### ISSUE TITLE
Is it similar to ProphetNet, ProphetNet-Ads and BANG?

### ISSUE THREAD

**Issue by qiweizhen** [hao-ai-lab/LookaheadDecoding#24]

**Comment by qiweizhen** [comment]
https://arxiv.org/abs/2001.04063 
ProphetNet, a looking head strategy for parallel decoding, 
and 
https://arxiv.org/abs/2010.10789
ProphetNet-Ads, a deployment of this looking ahead generation model.

**Comment by Viol2000** [comment]
Hi, thanks for your interest!

I just read your paper and found it is quite different.
