### ISSUE TITLE
question about attention patterns

### ISSUE THREAD

**Issue by FrankCast1e** [hao-ai-lab/LookaheadDecoding#28]
Hi! 
In Figure 5 of the blog, it seems like tokens of the current iteration attend to tokens from previous iterations. For example, the token at position 6 in red attends to token at position 5 in green. 
But in Jacobi decoding, is it supposed to attend to tokens from the current iteration? That is: the token at position 6 in red attends to token at position 5 in red.

**Comment by FrankCast1e** [comment]
Thank you for your reply! I'm still a little bit confused.
1. Without the basic form of Jacobi decoding,  how to guarantee that lookahead decoding has the exact same results as autoregressive decoding?
2. From my understanding, if the sequence is [a, b, c, d, e] and "c" is position 0, then "e" is position 2, is that right?

**Comment by FrankCast1e** [comment]
In Figure 5, position 6 in red actually attends to position 5 in green (as the red arrow), instead of position 5 in red (as the green arrow). Why is that, considering that position 5 in red is the latest iteration result? So, you can get a more accurate trajectory by attention like this?
<img width="665" alt="image" src="https://github.com/hao-ai-lab/LookaheadDecoding/assets/47963924/e191baf4-8da1-491c-914c-4d75b29d3924">

**Comment by Viol2000** [comment]
Hi @FrankCast1e , my idea is that the red 6 is generated by the sequence: some 3, orange 4, green 5. This makes a strong local relation if these 3,4,5 tokens can form an n-gram phase. In this turn, we can use orange 4, green 5, and red 6 to generate the next token to form another meaningful n-gram. If you use red 5 as the previous token of red 6, I think it does not make much sense as the red 6 has no relationship with red5, and it may not generate a meaningful n-gram. 
And, if you change the last token of red 6, which will be the last token of red 5? I think it should be carefully investigated and form another substitute solution.

**Comment by FrankCast1e** [comment]
Thank you very much for your explanation! I totally get the idea right now.
