### ISSUE TITLE
Any plan to support other LLMs, and integrated into huggingface? 

### ISSUE THREAD

**Issue by henryxiao1997** [hao-ai-lab/LookaheadDecoding#39]
Do you have the plan to support Mistral, Sola, Falcon (licence friendly models)?  Roughly the timeline?

Also, do you plan to integrate into huggingface to benefit broader audiences? 

Keen to see that! 

Thanks!

**Comment by Viol2000** [comment]
Yes, we plan to support other LLMs, and I think it will not take long. 
We are also planning to integrate it into huggingface.

**Comment by henryxiao1997** [comment]
That's great! Thank you!

**Comment by henryxiao1997** [comment]
That's great! Thank you!
