### ISSUE TITLE
Undefined symbols in lade/decoding.py

### ISSUE THREAD

**Issue by hjmus** [hao-ai-lab/LookaheadDecoding#42]
The following symbols are undefined in lade/decoding.py:
- `validate_stopping_criteria`
- `window_cache`
- `GreedySearchEncoderDecoderOutput`
- `GreedySearchDecoderOnlyOutput`

**Comment by Viol2000** [comment]
Hi, thanks for your interest. You can use a later version of transformers to support these features.
