### ISSUE TITLE
Tensor parallel

### ISSUE THREAD

**Issue by wangyuwen1999** [hao-ai-lab/LookaheadDecoding#58]
<img width="1008" alt="截屏2024-04-15 11 13 09" src="https://github.com/hao-ai-lab/LookaheadDecoding/assets/43462373/660999f8-c418-4ba2-8ecd-dd4c63fc1d13">
I want to use tensor parallel with lookhead, but I do not find the  config to start the tensor parallel, can you give me an example?

**Comment by Viol2000** [comment]
Tensor parallel is not compatible with lookhead yet.
You can choose only to use tensor parallel (and no lookahead). L28-L35 in your figure is an example if you set GPUS larger.

**Comment by lethean1** [comment]
Is tensor parallel available now?
