### ISSUE TITLE
AttributeError: module 'lade' has no attribute 'config_pading'

### ISSUE THREAD

**Issue by liHai001** [hao-ai-lab/LookaheadDecoding#7]
run git repo demo with:
lade.config_pading(LEVEL=5, WINDOW_SIZE=7, GUESS_SET_SIZE=7, DEBUG=0)

error: AttributeError: module 'lade' has no attribute 'config_pading'

**Comment by Viol2000** [comment]
Sorry, we made a mistake. Please use 'config_lade' instead.
